service: aws-serverless-http-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello: 
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
 