service: aws-serverless-http-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatement:
    - Efeect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:162677776117:table/TodoTabl

functions:
  addTodo: 
    handler: src/addTodo.handler
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTabl
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

 